### ISSUE TITLE
--patch_based_backend GPU or CUDA didn't work

### ISSUE THREAD

**Issue by TombasOnly** [OndrejTexler/Neurally-Guided-Style-Transfer#1]
Hello, is gpu already implemented?
I've got this results:

--patch_based_backend GPU
FATAL ERROR: Internal error 9625

--patch_based_backend CUDA
nothing happens

Thanks for answer...

**Comment by OndrejTexler** [comment]
Hello. Actually, it is implemented and the only thing missing is to compile it using `nvcc` instead of `cl` or `g++` - I just did not have time to do it and test it. Honestly, I did not have time to polish the repository at all. I plan to do it in the next few days.

**Comment by TombasOnly** [comment]
Thanks for answer. This is a very cool project. I get very interesting results, when used with https://github.com/ProGamerGov/neural-style-pt or others. 
I appreciate every next update. Good luck with your project. :-)
