### ISSUE TITLE
nvcc fatal 

### ISSUE THREAD

**Issue by ayutools** [OndrejTexler/Neurally-Guided-Style-Transfer#5]
run build-win_cuda.bat  
 nvcc fatal  : Value 'compute_30' is not defined for option 'gpu-architecture' FAILED

NVIDIA GeForce RTX 3090

**Comment by OndrejTexler** [comment]
Hello. Yes, you are using new GPU. Try change `-arch` argument in `build-win_cuda.bat` script to some different architecture, for example, `-arch compute_53`.

Hope it helps! -Ondrej
